version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - 5000:80
    networks:
      - slut-network
    depends_on:
      - nuxt
      - wp

  nuxt:
    build: ./nuxt-wp
    restart: always
    networks:
      - slut-network
    depends_on:
      - mysql
      - wp
    command: npm run dev

  mysql:
    image: mysql:latest
    restart: always
    networks:
      - slut-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: haberol
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql

  wp:
    build: ./wordpress
    restart: always
    networks:
      - slut-network
    depends_on:
      - mysql
    volumes:
      - ./wordpress/tailpress:/app/wordpress/wp-content/themes/tailpress
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: haberol

volumes:
  mysql:
networks:
  slut-network:


